api_query_interval: 0.0
backend: triton
budget_tokens: 0
check_kernel: true
custom_prompt_key: None
dataset_name: ScalingIntelligence/KernelBench
dataset_src: huggingface
hardware_gpu_name: None
include_hardware_info: false
is_reasoning_model: false
level: 1
log_prompt: false
max_tokens: 8192
model_name: google/gemma-4-31B-it
num_samples: 10
num_workers: 10
precision: fp32
prompt_option: one_shot
reasoning_effort: low
run_name: morpheus_gemma4_level1_triton_sampled
runs_dir: /home/jan/KernelBench/runs
server_type: local
store_type: local
subset:
- null
- null
temperature: 0.6
verbose: false
